In [2]:
import numpy as np   
import pandas as pd  
import matplotlib.pyplot as plt  
import seaborn as sns   
from sklearn.model_selection import train_test_split  
from sklearn.preprocessing import StandardScaler, LabelEncoder  
from sklearn.svm import SVC  
from sklearn.metrics import accuracy_score, classification_report ,confusion_matrix  
import joblib

In [3]:
from sklearn.datasets import load_iris   #importing the dataset from sklearn

In [4]:
data =load_iris()   #Loading the Iris dataset from Scikit-learn

In [5]:
data  #the data is stored in the form of dictionary

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
df = pd.DataFrame(data.data,columns=data.feature_names)   # converting the data into dataframe

In [7]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [8]:
data.target   #the target is stored in the form of array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
df['target']=data.target  #adding the target column

In [10]:
df['target_names'] = df['target'].map({i:name for i ,name in enumerate(data.target_names)})   #adding the new target_names column 

In [11]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
 5   target_names       150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [13]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
target_names         0
dtype: int64

In [14]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [15]:
df['target_names'].value_counts()  #the target names are setosa,versicolor,virginica

target_names
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

## Binary classification

using SVC

in binary classification we use only two classes from target column, it has total of 3 classes in total [0:setosa, 1:versicolor, 2:virginica]

In [16]:
binary_df = df[df['target']!=2]  #dropping the virginica 

In [17]:
binary_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target target_names  
0        0       setosa  
1        0       setosa  
2        0       setosa  
3        0       setosa  
4        0       setosa  
..     ...          ...  
95       1   versicolor  
96       1   versicolor  
97       1   versicolor  
98       1   versicolor  
99       1   versicolor  

[100 rows x 6 columns]

In [18]:
binary_df['target_names'].unique()  #the target names are setosa and versicolor i.e 0 and 1

array(['setosa', 'versicolor'], dtype=object)

In [19]:
binary_df['target'].unique()

array([0, 1])

In [20]:
x_binary=binary_df.drop(columns=['target','target_names'])   #dropping the target and target_names
y_binary=binary_df['target']  #only the target column

In [21]:
x_binary

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [22]:
y_binary

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int64

In [23]:
x_train,x_test,y_train,y_test =  train_test_split(x_binary,y_binary,test_size=0.2 ,random_state=42)   #Splitting dataset into training and testing sets where 80% of the data is used for training and 20% for testing  

In [24]:
x_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
55                5.7               2.8                4.5               1.3
88                5.6               3.0                4.1               1.3
26                5.0               3.4                1.6               0.4
42                4.4               3.2                1.3               0.2
69                5.6               2.5                3.9               1.1
..                ...               ...                ...               ...
60                5.0               2.0                3.5               1.0
71                6.1               2.8                4.0               1.3
14                5.8               4.0                1.2               0.2
92                5.8               2.6                4.0               1.2
51                6.4               3.2                4.5               1.5

[80 rows x 4 columns]

In [25]:
x_test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
83                6.0               2.7                5.1               1.6
53                5.5               2.3                4.0               1.3
70                5.9               3.2                4.8               1.8
45                4.8               3.0                1.4               0.3
44                5.1               3.8                1.9               0.4
39                5.1               3.4                1.5               0.2
22                4.6               3.6                1.0               0.2
80                5.5               2.4                3.8               1.1
10                5.4               3.7                1.5               0.2
0                 5.1               3.5                1.4               0.2
18                5.7               3.8                1.7               0.3
30                4.8               3.1                1.6               0.2
73                6.1               2.8                4.7               1.2
33                5.5               4.2                1.4               0.2
90                5.5               2.6                4.4               1.2
4                 5.0               3.6                1.4               0.2
76                6.8               2.8                4.8               1.4
77                6.7               3.0                5.0               1.7
12                4.8               3.0                1.4               0.1
31                5.4               3.4                1.5               0.4

In [26]:
print(y_binary.value_counts()) 

target
0    50
1    50
Name: count, dtype: int64


In [27]:
scaler = StandardScaler()     #Creating a StandardScaler instance for feature scaling
x_train_scaled =scaler.fit_transform(x_train)  #fitting the data 
x_test_scaled = scaler.transform(x_test)    #transforming the data

Initialize a binary Support Vector Machine (SVM) classifier with a linear kernel

SVC is used find the optimal hyperplane that separates classes in the feature space

In [28]:
svm_binary = SVC(kernel='linear', C=1.0, probability=True)    #C is the regularization parameter 

In [29]:
svm_binary.fit(x_train_scaled,y_train)  #fitting the data

SVC(kernel='linear', probability=True)

In [30]:
svm_binary.predict(x_test_scaled)   #predicting the data

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [31]:
print(classification_report(y_test,svm_binary.predict(x_test_scaled)))  #printing the classification report  # Generating a classification report

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [32]:
confusion_matrix(y_test,svm_binary.predict(x_test_scaled))   #printing the confusion matrix  # Creating a confusion matrix

array([[12,  0],
       [ 0,  8]])

In [33]:
joblib.dump(svm_binary,'svm_binary.pkl')   #Saving the trained model using joblib

['svm_binary.pkl']

In [34]:
# Save the scaler 
joblib.dump(scaler, 'svm_binary_scaler.pkl')  #Saving the trained model using joblib

['svm_binary_scaler.pkl']

# Multiclass Classifcaiton

In [35]:
x_multi = df[['sepal length (cm)',	'sepal width (cm)',	 'petal length (cm)',  'petal width (cm)']]

In [36]:
x_multi  

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [37]:
y_multi = df['target']

In [38]:
y_multi

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [39]:
x_train_multi , x_test_multi , y_train_multi , y_test_multi = train_test_split(x_multi, y_multi, test_size= 0.2, random_state= 42)  # splitting the data into train and test   # Splitting dataset into training and testing sets

In [40]:
svm_multi = SVC(kernel="linear") # initializing the model 

In [41]:
svm_multi.fit(x_train_multi,y_train_multi)  # fitting the data

SVC(kernel='linear')

In [42]:
svm_multi.predict(x_test_multi)    # predicting the data

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [43]:
print("report for multi class svc \n",classification_report(y_test_multi ,svm_multi.predict(x_test_multi) ))   #printing the classification report  # Generating a classification report

report for multi class svc 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [44]:
confusion_matrix(y_test_multi ,svm_multi.predict(x_test_multi))   #printing the confusion matrix  # Creating a confusion matrix

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [45]:
joblib.dump(svm_multi,"svm_multi.pkl")  #Saving the trained model using joblib

['svm_multi.pkl']

# Logistic Regression

#### Binary Logistic Regression used for binary classification problems

In [46]:
x_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
55                5.7               2.8                4.5               1.3
88                5.6               3.0                4.1               1.3
26                5.0               3.4                1.6               0.4
42                4.4               3.2                1.3               0.2
69                5.6               2.5                3.9               1.1
..                ...               ...                ...               ...
60                5.0               2.0                3.5               1.0
71                6.1               2.8                4.0               1.3
14                5.8               4.0                1.2               0.2
92                5.8               2.6                4.0               1.2
51                6.4               3.2                4.5               1.5

[80 rows x 4 columns]

In [47]:
x_test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
83                6.0               2.7                5.1               1.6
53                5.5               2.3                4.0               1.3
70                5.9               3.2                4.8               1.8
45                4.8               3.0                1.4               0.3
44                5.1               3.8                1.9               0.4
39                5.1               3.4                1.5               0.2
22                4.6               3.6                1.0               0.2
80                5.5               2.4                3.8               1.1
10                5.4               3.7                1.5               0.2
0                 5.1               3.5                1.4               0.2
18                5.7               3.8                1.7               0.3
30                4.8               3.1                1.6               0.2
73                6.1               2.8                4.7               1.2
33                5.5               4.2                1.4               0.2
90                5.5               2.6                4.4               1.2
4                 5.0               3.6                1.4               0.2
76                6.8               2.8                4.8               1.4
77                6.7               3.0                5.0               1.7
12                4.8               3.0                1.4               0.1
31                5.4               3.4                1.5               0.4

In [48]:
y_train

55    1
88    1
26    0
42    0
69    1
     ..
60    1
71    1
14    0
92    1
51    1
Name: target, Length: 80, dtype: int64

In [49]:
y_test

83    1
53    1
70    1
45    0
44    0
39    0
22    0
80    1
10    0
0     0
18    0
30    0
73    1
33    0
90    1
4     0
76    1
77    1
12    0
31    0
Name: target, dtype: int64

In [50]:
from sklearn.linear_model import LogisticRegression

In [51]:
x_train_scaled

array([[ 0.34989908, -0.5881428 ,  1.13555602,  0.89744481],
       [ 0.19609729, -0.16040258,  0.8521099 ,  0.89744481],
       [-0.72671348,  0.69507785, -0.91942835, -0.73427302],
       [-1.64952424,  0.26733764, -1.13201294, -1.09687699],
       [ 0.19609729, -1.22975312,  0.71038684,  0.53484084],
       [ 0.34989908,  2.83377893, -0.99028988, -0.73427302],
       [-0.72671348,  0.90894796, -1.13201294, -0.91557501],
       [ 0.34989908, -0.37427269,  0.92297143,  0.89744481],
       [-0.88051527,  0.05346753, -0.99028988, -1.27817897],
       [ 1.27270985, -1.22975312,  1.41900214,  1.26004877],
       [-1.03431707,  0.69507785, -0.91942835, -1.09687699],
       [-1.34192066,  0.26733764, -1.06115141, -1.09687699],
       [ 0.81130447,  0.69507785,  1.13555602,  1.44135075],
       [-0.41910989,  0.69507785, -1.06115141, -1.09687699],
       [-0.72671348, -1.65749334,  0.28521766,  0.35353886],
       [-0.1115063 ,  1.76442839, -0.84856682, -0.73427302],
       [ 0.19609729, -0.

In [52]:
logistics_binary = LogisticRegression()
logistics_binary.fit(x_train_scaled,y_train)

LogisticRegression()

In [53]:
y_pred = logistics_binary.predict(x_test_scaled)
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [54]:
print(classification_report(y_test,y_pred))  # Generating a classification report i.e actual and predicted

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [55]:
confusion_matrix(y_test,y_pred)  # Creating a confusion matrix i.e actual and predicted

array([[12,  0],
       [ 0,  8]])

In [56]:
joblib.dump(logistics_binary,'logistics_binary.pkl')  # Saving the trained model using joblib

['logistics_binary.pkl']

# Multiclass Classification

#### Multiclass Logistic Regression:



In [57]:
x_train_multi 

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                 4.6               3.6                1.0               0.2
15                 5.7               4.4                1.5               0.4
65                 6.7               3.1                4.4               1.4
11                 4.8               3.4                1.6               0.2
42                 4.4               3.2                1.3               0.2
..                 ...               ...                ...               ...
71                 6.1               2.8                4.0               1.3
106                4.9               2.5                4.5               1.7
14                 5.8               4.0                1.2               0.2
92                 5.8               2.6                4.0               1.2
102                7.1               3.0                5.9               2.1

[120 rows x 4 columns]

In [58]:
x_test_multi

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73                 6.1               2.8                4.7               1.2
18                 5.7               3.8                1.7               0.3
118                7.7               2.6                6.9               2.3
78                 6.0               2.9                4.5               1.5
76                 6.8               2.8                4.8               1.4
31                 5.4               3.4                1.5               0.4
64                 5.6               2.9                3.6               1.3
141                6.9               3.1                5.1               2.3
68                 6.2               2.2                4.5               1.5
82                 5.8               2.7                3.9               1.2
110                6.5               3.2                5.1               2.0
12                 4.8               3.0                1.4               0.1
36                 5.5               3.5                1.3               0.2
9                  4.9               3.1                1.5               0.1
19                 5.1               3.8                1.5               0.3
56                 6.3               3.3                4.7               1.6
104                6.5               3.0                5.8               2.2
69                 5.6               2.5                3.9               1.1
55                 5.7               2.8                4.5               1.3
132                6.4               2.8                5.6               2.2
29                 4.7               3.2                1.6               0.2
127                6.1               3.0                4.9               1.8
26                 5.0               3.4                1.6               0.4
128                6.4               2.8                5.6               2.1
131                7.9               3.8                6.4               2.0
145                6.7               3.0                5.2               2.3
108                6.7               2.5                5.8               1.8
143                6.8               3.2                5.9               2.3
45                 4.8               3.0                1.4               0.3
30                 4.8               3.1                1.6               0.2

In [59]:
y_train_multi

22     0
15     0
65     1
11     0
42     0
      ..
71     1
106    2
14     0
92     1
102    2
Name: target, Length: 120, dtype: int64

In [60]:
y_test_multi

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
110    2
12     0
36     0
9      0
19     0
56     1
104    2
69     1
55     1
132    2
29     0
127    2
26     0
128    2
131    2
145    2
108    2
143    2
45     0
30     0
Name: target, dtype: int64

In [61]:
logistics_ovr = LogisticRegression(multi_class='ovr',solver='lbfgs',max_iter=2000)

In [62]:
logistics_ovr.fit(x_train_multi,y_train_multi)

LogisticRegression(max_iter=2000, multi_class='ovr')

In [63]:
logistics_ovr.predict(x_test_multi)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [64]:
print("classificatoin repost for ovr logistics \n" , classification_report(y_test_multi , logistics_ovr.predict(x_test_multi)))  # Generating a classification report

classificatoin repost for ovr logistics 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



In [65]:
confusion_matrix(y_test_multi , logistics_ovr.predict(x_test_multi))  # Creating a confusion matrix

array([[10,  0,  0],
       [ 0,  8,  1],
       [ 0,  0, 11]])

In [66]:
joblib.dump(logistics_ovr,'logistic_ovr.pkl')  # Saving the trained model using joblib

['logistic_ovr.pkl']

##  Multinomial Logistic Regression:



In [67]:
logistics_multinomial  = LogisticRegression(multi_class='multinomial',solver='lbfgs',max_iter=2000)

In [68]:
logistics_multinomial.fit(x_train_multi,y_train_multi)

LogisticRegression(max_iter=2000, multi_class='multinomial')

In [69]:
confusion_matrix(y_test_multi,logistics_multinomial.predict(x_test_multi) )  # Creating a confusion matrix

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [70]:
print("the classificatoin report for multinomial multi class logistics is \n" , classification_report(y_test_multi,logistics_multinomial.predict(x_test_multi) ))  # Generating a classification report

the classificatoin report for multinomial multi class logistics is 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [71]:
joblib.dump(logistics_multinomial,'logistics_multinomial.pkl')  # Saving the trained model using joblib

['logistics_multinomial.pkl']